"use client"

import { useOrganization } from '@/components/providers/organization-provider'
import { pluralize } from '@/lib/pluralize'

/**
 * Hook legado refatorado para usar o OrganizationProvider central.
 * Mantém compatibilidade com o código que já usa useVocabulary.
 */
export function useVocabulary() {
  const { 
    vocabulary, 
    niche, 
    enabledModules, 
    isLoading,
    language
  } = useOrganization()

  // Traduções para Inglês se o idioma for 'en'
  const translatedVocab = language === 'en' ? {
    ...vocabulary,
    client: translateToEnglish(vocabulary.client),
    provider: translateToEnglish(vocabulary.provider),
    service: translateToEnglish(vocabulary.service),
    establishment: translateToEnglish(vocabulary.establishment),
    category: translateToEnglish(vocabulary.category)
  } : vocabulary

  // Adiciona versões plurais automaticamente
  const pluralVocabulary = {
    ...translatedVocab,
    clients: pluralize(translatedVocab.client),
    providers: pluralize(translatedVocab.provider),
    services: pluralize(translatedVocab.service),
    establishments: pluralize(translatedVocab.establishment)
  }

  return { 
    vocabulary: pluralVocabulary, 
    niche, 
    schemas: {}, 
    enabledModules, 
    loading: isLoading,
    language
  }
}

// Helper simples para tradução de termos de vocabulário
function translateToEnglish(term: string): string {
  const dictionary: Record<string, string> = {
    'Aluno': 'Student',
    'Professor': 'Teacher',
    'Aula': 'Class',
    'Estúdio': 'Studio',
    'Modalidade': 'Category',
    'Paciente': 'Patient',
    'Doutor': 'Doctor',
    'Consulta': 'Appointment',
    'Consultório': 'Office',
    'Especialidade': 'Specialty',
    'Membro': 'Member',
    'Instrutor': 'Instructor',
    'Treino': 'Workout',
    'Academia': 'Gym',
    'Médico': 'Doctor',
    'Exame': 'Exam',
    'Clínica': 'Clinic',
    'Cliente': 'Client',
    'Profissional': 'Professional',
    'Procedimento': 'Procedure',
    'Salão': 'Salon',
    'Serviço': 'Service',
    'Esteticista': 'Aesthetician',
    'Sessão': 'Session',
    'Nível': 'Level',
    'Prática': 'Practice',
    'Barbeiro': 'Barber',
    'Barbearia': 'Barbershop',
    'Corte': 'Cut',
    'Terapeuta': 'Therapist',
    'Massagem': 'Massage',
    'Fisioterapeuta': 'Physiotherapist',
    'Nutricionista': 'Nutritionist',
    'Plano': 'Plan',
    'Podólogo': 'Podiatrist',
    'Atendimento': 'Service',
    'Atendente': 'Attendant',
    'Tutor': 'Owner',
    'Tosador': 'Groomer',
    'Banho/Tosa': 'Grooming',
    'Pet Shop': 'Pet Shop',
    'Veterinário': 'Vet',
    'Creche Canina': 'Dog Daycare',
    'Monitor': 'Monitor',
    'Diária': 'Day use',
    'Creche': 'Daycare',
    'Atividade': 'Activity',
    'Adestrador': 'Trainer',
    'Centro': 'Center',
    'Hóspede': 'Guest',
    'Cuidador': 'Caretaker',
    'Hospedagem': 'Lodging',
    'Hotel': 'Hotel',
    'Acomodação': 'Accommodation',
    'Artes Marciais': 'Martial Arts',
    'Sensei': 'Sensei',
    'Dojo': 'Dojo',
    'Atleta': 'Athlete',
    'Coach': 'Coach',
    'WOD': 'WOD',
    'Box': 'Box',
    'Natação': 'Swimming',
    'Escola': 'School',
    'Personal Trainer': 'Personal Trainer',
    'Personal': 'Trainer',
    'Consultoria': 'Consultancy',
    'Foco': 'Focus',
    'Beach Tennis': 'Beach Tennis',
    'Arena': 'Arena',
    'Escola de Música': 'Music School',
    'Instrumento': 'Instrument',
    'Escola de Idiomas': 'Language School',
    'Teacher': 'Teacher',
    'Idioma': 'Language',
    'Ateliê de Arte': 'Art Studio',
    'Workshop': 'Workshop',
    'Ateliê': 'Studio',
    'Técnica': 'Technique',
    'Gastronomia': 'Gastronomy',
    'Chef': 'Chef',
    'Culinária': 'Cooking',
    'Fotografia (Escola)': 'Photography (School)',
    'Fotógrafo': 'Photographer',
    'Curso': 'Course',
    'Estética Automotiva': 'Auto Detailing',
    'Oficina Mecânica': 'Auto Repair',
    'Mecânico': 'Mechanic',
    'Reparo': 'Repair',
    'Oficina': 'Shop',
    'Lava-jato': 'Car Wash',
    'Lavador': 'Washer',
    'Lavagem': 'Wash',
    'Serviços de Limpeza': 'Cleaning Services',
    'Limpeza': 'Cleaning',
    'Empresa': 'Company',
    'Design de Interiores': 'Interior Design',
    'Designer': 'Designer',
    'Projeto': 'Project',
    'Escritório': 'Office',
    'Espaço de Eventos': 'Event Space',
    'Contratante': 'Contractor',
    'Organizador': 'Organizer',
    'Evento': 'Event',
    'Espaço': 'Space',
    'Fotógrafo (Studio)': 'Photographer (Studio)',
    'Ensaio': 'Shoot',
    'Coworking': 'Coworking',
    'Coworker': 'Coworker',
    'Gestor': 'Manager',
    'Reserva': 'Booking',
    'Tattoo & Piercing': 'Tattoo & Piercing',
    'Tatuador': 'Tattoo Artist',
    'Assistência Técnica': 'Tech Support',
    'Técnico': 'Technician',
    'Assistência': 'Support',
    'Aparelho': 'Device',
    'Advocacia': 'Law',
    'Advogado': 'Lawyer',
    'Processo': 'Process',
    'Área': 'Area',
    'Psicologia': 'Psychology',
    'Psicólogo': 'Psychologist',
    'Abordagem': 'Approach',
    'Clube do Vinho': 'Wine Club',
    'Sócio': 'Member',
    'Sommelier': 'Sommelier',
    'Degustação': 'Tasting',
    'Clube': 'Club',
    'Cervejaria': 'Brewery',
    'Mestre': 'Master',
    'Cafeteria/Barista': 'Coffee Shop/Barista',
    'Barista': 'Barista',
    'Grão': 'Bean',
    'Confeitaria': 'Bakery',
    'Confeiteiro': 'Baker',
    'Encomenda': 'Order',
    'Produto': 'Product',
    'Imobiliária': 'Real Estate',
    'Corretor': 'Realtor',
    'Visita': 'Visit',
    'Imóvel': 'Property',
    'Consultor': 'Consultant',
    'Reunião': 'Meeting',
    'Agência de Marketing': 'Marketing Agency',
    'Analista': 'Analyst',
    'Campanha': 'Campaign',
    'Agência': 'Agency',
    'Canal': 'Channel',
    'Desenvolvimento': 'Development',
    'Dev': 'Developer',
    'Sprint': 'Sprint',
    'Tech': 'Tech',
    'Organização de Eventos': 'Event Planning',
    'Agência de Viagens': 'Travel Agency',
    'Agente': 'Agent',
    'Roteiro': 'Itinerary',
    'Destino': 'Destination',
    'Corretora de Seguros': 'Insurance Broker',
    'Segurado': 'Insured',
    'Apólice': 'Policy',
    'Corretora': 'Brokerage',
    'Ramo': 'Branch',
    'Paisagismo': 'Landscaping',
    'Paisagista': 'Landscaper',
    'Manutenção': 'Maintenance',
    'Encanador': 'Plumber',
    'Eletricista': 'Electrician',
    'Instalação': 'Installation',
    'Construção Civil': 'Construction',
    'Engenheiro': 'Engineer',
    'Obra': 'Construction Site',
    'Etapa': 'Stage',
    'Logística': 'Logistics',
    'Entregador': 'Delivery person',
    'Entrega': 'Delivery',
    'Transportadora': 'Carrier',
    'Rota': 'Route',
    'Alfaiataria/Costura': 'Tailoring/Sewing',
    'Costureiro(a)': 'Tailor',
    'Ajuste': 'Adjustment',
    'Peça': 'Garment',
    'Aulas Particulares': 'Tutoring',
    'Local': 'Location',
    'Matéria': 'Subject',
    'Creche Infantil': 'Daycare',
    'Responsável': 'Parent/Guardian',
    'Casa de Repouso': 'Nursing Home',
    'Residente': 'Resident',
    'Casa': 'Home',
    'Cuidados': 'Care',
    'Auto Escola': 'Driving School',
    'CFC': 'Driving School',
    'Categoria': 'Category',
    'Aula Prática': 'Driving Class'
  }
  return dictionary[term] || term
}
